import { storage } from "./storage";
import { seedOrgRoles } from "./seed-org-roles";

export async function seedDatabase() {
  await seedOrgRoles();

  const existingAgents = await storage.getAgents();
  if (existingAgents.length > 0) return;

  const agents = await Promise.all([
    storage.createAgent({
      name: "Security Monitor",
      type: "security_monitor",
      description: "Continuously monitors security logs, detects threats, analyzes vulnerabilities, and generates real-time alerts for suspicious activities across all infrastructure endpoints.",
      status: "active",
      capabilities: ["Log Analysis", "Threat Detection", "Vulnerability Scanning", "Real-time Alerting", "SIEM Correlation"],
      icon: "Shield",
      color: "#2563eb",
    }),
    storage.createAgent({
      name: "Incident Manager",
      type: "incident_manager",
      description: "Handles the full incident lifecycle from detection through resolution. Automates triage, assigns severity levels, coordinates response teams, and tracks resolution timelines.",
      status: "active",
      capabilities: ["Auto-Triage", "Severity Assignment", "Escalation Management", "Resolution Tracking", "Post-Mortem Analysis"],
      icon: "AlertTriangle",
      color: "#dc2626",
    }),
    storage.createAgent({
      name: "Service Desk",
      type: "service_desk",
      description: "Manages IT service requests from intake to fulfillment. Handles categorization, routing, SLA monitoring, and user communication throughout the service delivery process.",
      status: "active",
      capabilities: ["Request Intake", "Auto-Categorization", "SLA Monitoring", "User Communication", "Knowledge Base Search"],
      icon: "Headphones",
      color: "#16a34a",
    }),
    storage.createAgent({
      name: "Change Manager",
      type: "change_manager",
      description: "Oversees change management processes including request evaluation, impact assessment, approval workflows, implementation scheduling, and rollback planning.",
      status: "active",
      capabilities: ["Impact Assessment", "Approval Workflow", "Schedule Management", "Rollback Planning", "Compliance Checking"],
      icon: "GitBranch",
      color: "#9333ea",
    }),
    storage.createAgent({
      name: "Asset Manager",
      type: "asset_manager",
      description: "Tracks and manages IT assets throughout their lifecycle. Monitors hardware and software inventory, license compliance, and configuration baselines.",
      status: "active",
      capabilities: ["Asset Discovery", "License Tracking", "Lifecycle Management", "Config Baseline", "Deprecation Alerts"],
      icon: "Server",
      color: "#ca8a04",
    }),
    storage.createAgent({
      name: "Problem Analyst",
      type: "problem_analyst",
      description: "Performs root cause analysis on recurring incidents, identifies known errors, documents workarounds, and drives permanent solutions to reduce incident recurrence.",
      status: "active",
      capabilities: ["Root Cause Analysis", "Known Error DB", "Trend Analysis", "Workaround Documentation", "Proactive Problem Detection"],
      icon: "Search",
      color: "#e11d48",
    }),
    storage.createAgent({
      name: "Knowledge Manager",
      type: "knowledge_manager",
      description: "Curates and maintains the knowledge base, ensures articles are accurate and up-to-date, tracks article effectiveness, and identifies knowledge gaps.",
      status: "active",
      capabilities: ["Article Management", "Content Review", "Gap Analysis", "Search Optimization", "Usage Analytics"],
      icon: "BookOpen",
      color: "#0d9488",
    }),
    storage.createAgent({
      name: "SLA Monitor",
      type: "sla_monitor",
      description: "Tracks service level agreement compliance across all tickets. Monitors response and resolution times, triggers escalations, and generates SLA performance reports.",
      status: "active",
      capabilities: ["SLA Tracking", "Breach Alerting", "Escalation Triggers", "Performance Reporting", "Trend Forecasting"],
      icon: "Clock",
      color: "#f59e0b",
    }),
    storage.createAgent({
      name: "AI Master",
      type: "master",
      description: "The orchestrating intelligence that coordinates all specialist agents. Routes user queries, delegates tasks, aggregates insights, and provides a unified interface for SIEM & ITSM operations.",
      status: "active",
      capabilities: ["Agent Coordination", "Task Delegation", "Report Aggregation", "Natural Language Interface", "Decision Support"],
      icon: "Brain",
      color: "#0891b2",
    }),
    storage.createAgent({
      name: "Network Monitor",
      type: "network_monitor",
      description: "Autonomously monitors all network infrastructure via SNMP, SSH, and NetFlow. Performs real-time bandwidth analysis, detects anomalies, and auto-remediates network issues without human intervention.",
      status: "active",
      capabilities: ["SNMP Polling", "NetFlow Analysis", "Bandwidth Monitoring", "Port Scanning", "Auto-Failover", "Route Optimization"],
      icon: "Network",
      color: "#6366f1",
    }),
    storage.createAgent({
      name: "IoT Controller",
      type: "iot_controller",
      description: "Manages all IoT devices and edge infrastructure via MQTT and REST APIs. Handles firmware updates, sensor data collection, anomaly detection, and automatic device provisioning.",
      status: "active",
      capabilities: ["MQTT Monitoring", "Firmware Management", "Sensor Analytics", "Device Provisioning", "Edge Computing", "Protocol Translation"],
      icon: "Cpu",
      color: "#ec4899",
    }),
    storage.createAgent({
      name: "Automation Engine",
      type: "automation_engine",
      description: "Executes autonomous remediation playbooks across the entire infrastructure. Handles automated patching, service restarts, scaling operations, and configuration drift correction.",
      status: "active",
      capabilities: ["Playbook Execution", "Auto-Remediation", "Configuration Drift", "Scaling Operations", "Rollback Automation", "Scheduled Maintenance"],
      icon: "Zap",
      color: "#f97316",
    }),
    storage.createAgent({
      name: "Compliance Auditor",
      type: "compliance_auditor",
      description: "Continuously audits infrastructure for compliance with security policies, regulatory frameworks (SOC2, ISO27001, HIPAA), and internal standards. Auto-generates compliance reports.",
      status: "active",
      capabilities: ["Policy Enforcement", "Regulatory Compliance", "Audit Trail", "Risk Assessment", "Remediation Recommendations", "Report Generation"],
      icon: "FileCheck",
      color: "#14b8a6",
    }),
    storage.createAgent({
      name: "Patch Manager",
      type: "patch_manager",
      description: "Autonomously manages patching across all servers, workstations, and network devices. Evaluates CVE severity, schedules maintenance windows, and validates patch success.",
      status: "active",
      capabilities: ["CVE Assessment", "Patch Scheduling", "Rollback Management", "Compatibility Testing", "Firmware Updates", "Zero-Day Response"],
      icon: "Download",
      color: "#8b5cf6",
    }),
  ]);

  const [securityAgent, incidentAgent, serviceAgent, changeAgent, assetAgent, problemAgent, knowledgeAgent, slaAgent, masterAgent, networkAgent, iotAgent, automationAgent, complianceAgent, patchAgent] = agents;

  await Promise.all([
    storage.createIncident({ title: "Unauthorized SSH Access Attempt Detected", description: "Multiple failed SSH login attempts detected from IP 192.168.45.102 targeting the production database server. Brute force pattern identified with 847 attempts in the last 30 minutes.", severity: "critical", status: "open", category: "Unauthorized Access", source: "Firewall IDS", assignedAgentId: incidentAgent.id }),
    storage.createIncident({ title: "Malware Signature Found in Email Attachment", description: "Phishing email with malicious PDF attachment detected in the email gateway. The attachment contains a known Emotet variant. 3 users have received the email but none have opened the attachment.", severity: "high", status: "investigating", category: "Malware", source: "Email Security Gateway", assignedAgentId: incidentAgent.id }),
    storage.createIncident({ title: "Anomalous Data Exfiltration Pattern", description: "Unusual outbound data transfer of 2.3GB detected from workstation WS-0234 to an external IP in a non-standard country. Data loss prevention rules triggered.", severity: "high", status: "open", category: "Data Exfiltration", source: "DLP System", assignedAgentId: securityAgent.id }),
    storage.createIncident({ title: "SSL Certificate Expiring in 7 Days", description: "The wildcard SSL certificate for *.internal.company.com is expiring on March 10, 2026. Automatic renewal failed due to DNS validation issues.", severity: "medium", status: "in_progress", category: "Certificate Management", source: "Certificate Monitor", assignedAgentId: serviceAgent.id }),
    storage.createIncident({ title: "Privilege Escalation Attempt Blocked", description: "User account 'j.smith' attempted to execute administrative commands without proper authorization on server PROD-APP-03. The attempt was automatically blocked by endpoint protection.", severity: "medium", status: "resolved", category: "Privilege Escalation", source: "Endpoint Protection", assignedAgentId: incidentAgent.id }),
    storage.createIncident({ title: "IoT Sensor Network Latency Spike", description: "MQTT broker reporting 300ms+ latency on warehouse sensor mesh network. Temperature and humidity sensors in Zone C are delayed, risking cold-chain compliance violations.", severity: "high", status: "investigating", category: "IoT Performance", source: "IoT Controller Agent", assignedAgentId: iotAgent.id }),
    storage.createIncident({ title: "Switch Port Flapping on Core Switch", description: "Network Monitor Agent detected port Gi1/0/24 on CORE-SW-01 flapping every 15 seconds. Auto-remediation disabled the port and rerouted traffic via redundant path.", severity: "medium", status: "in_progress", category: "Network", source: "Network Monitor Agent", assignedAgentId: networkAgent.id }),
  ]);

  await Promise.all([
    storage.createServiceRequest({ title: "New Employee Onboarding - IT Setup", description: "Set up workstation, email account, VPN access, and required software licenses for new hire Sarah Chen starting March 10. Role: Security Analyst, Department: SOC.", type: "onboarding", priority: "high", status: "in_progress", assignedAgentId: serviceAgent.id }),
    storage.createServiceRequest({ title: "VPN Access Request for Remote Contractor", description: "External contractor from CyberDefense Corp needs VPN access to the staging environment for penetration testing engagement. Duration: 2 weeks.", type: "access_request", priority: "medium", status: "pending", assignedAgentId: serviceAgent.id }),
    storage.createServiceRequest({ title: "Software License Renewal - Splunk Enterprise", description: "Annual Splunk Enterprise license renewal due by March 15. Current license covers 500GB/day ingestion. Need to evaluate if we should upgrade to 750GB/day based on growing log volume.", type: "procurement", priority: "high", status: "pending", assignedAgentId: serviceAgent.id }),
    storage.createServiceRequest({ title: "Password Reset - Executive Account", description: "CFO account locked after multiple failed MFA attempts. Need immediate password reset and MFA token resync.", type: "password_reset", priority: "critical", status: "in_progress", assignedAgentId: serviceAgent.id }),
  ]);

  await Promise.all([
    storage.createSecurityEvent({ eventType: "intrusion_attempt", source: "Firewall", severity: "critical", message: "Repeated port scanning detected from external IP 45.33.32.156 targeting ports 22, 3389, 445", processed: true, detectedByAgentId: securityAgent.id }),
    storage.createSecurityEvent({ eventType: "authentication_failure", source: "Active Directory", severity: "high", message: "15 failed login attempts for service account 'svc_backup' within 5 minutes", processed: true, detectedByAgentId: securityAgent.id }),
    storage.createSecurityEvent({ eventType: "policy_violation", source: "DLP", severity: "medium", message: "Sensitive file 'Q1_financials.xlsx' uploaded to unauthorized cloud storage service", processed: false, detectedByAgentId: securityAgent.id }),
    storage.createSecurityEvent({ eventType: "malware_detected", source: "Endpoint Protection", severity: "critical", message: "Trojan.GenericKD.46542178 detected and quarantined on workstation WS-0891", processed: true, detectedByAgentId: securityAgent.id }),
    storage.createSecurityEvent({ eventType: "config_change", source: "CMDB", severity: "low", message: "Firewall rule FW-2847 modified: added exception for development subnet 10.20.30.0/24", processed: true, detectedByAgentId: securityAgent.id }),
    storage.createSecurityEvent({ eventType: "anomaly_detection", source: "UEBA", severity: "high", message: "User 'admin_ops' accessing resources at unusual hours (03:42 AM) from unfamiliar geolocation", processed: false, detectedByAgentId: securityAgent.id }),
    storage.createSecurityEvent({ eventType: "vulnerability_scan", source: "Qualys", severity: "medium", message: "CVE-2025-21298 (CVSS 7.8) found on 12 Windows servers - OLE remote code execution vulnerability", processed: false, detectedByAgentId: securityAgent.id }),
  ]);

  await Promise.all([
    storage.createProblem({ title: "Recurring VPN Connectivity Drops", description: "Multiple users reporting intermittent VPN disconnections during peak hours (9-11 AM). Pattern observed over the past 2 weeks affecting approximately 15% of remote workforce.", status: "investigating", priority: "high", category: "Network", rootCause: null, workaround: "Users can reconnect by switching to backup VPN gateway vpn-backup.company.com", knownError: true, affectedServices: ["VPN", "Remote Access"], relatedIncidentCount: 12, assignedAgentId: problemAgent.id }),
    storage.createProblem({ title: "Email Delivery Delays to External Recipients", description: "Outbound emails to external domains experiencing 15-30 minute delays. SMTP relay logs show queuing at the spam filter gateway. Started after firmware update on March 1.", status: "root_cause_identified", priority: "medium", category: "Email", rootCause: "Spam filter firmware v4.2.1 introduced a new scanning algorithm that increases processing time by 300% for attachments over 5MB", workaround: "Send large attachments via secure file sharing portal instead of email", knownError: true, affectedServices: ["Email", "SMTP Relay"], relatedIncidentCount: 8, assignedAgentId: problemAgent.id }),
    storage.createProblem({ title: "Intermittent Database Connection Pool Exhaustion", description: "Production application experiencing periodic database connection failures during batch processing windows. Connection pool hitting maximum limit causing cascading timeouts.", status: "open", priority: "critical", category: "Database", rootCause: null, workaround: null, knownError: false, affectedServices: ["CRM Application", "Reporting Dashboard", "API Gateway"], relatedIncidentCount: 5, assignedAgentId: problemAgent.id }),
    storage.createProblem({ title: "Print Server Spooler Crashes on Color Print Jobs", description: "Windows print server spooler service crashes when processing color print jobs larger than 50 pages. Black and white printing works fine. Affecting the Finance and Marketing departments.", status: "resolved", priority: "low", category: "Printing", rootCause: "Incompatible printer driver v3.8.2 for HP Color LaserJet Pro series. Driver memory leak during color rasterization.", workaround: "Split large color jobs into batches under 50 pages", knownError: true, affectedServices: ["Print Services"], relatedIncidentCount: 3, assignedAgentId: problemAgent.id }),
  ]);

  await Promise.all([
    storage.createChangeRequest({ title: "Upgrade Firewall Firmware to v7.2.4", description: "Critical security patch for firewall cluster addressing CVE-2025-3847. Requires 10-minute maintenance window for failover during upgrade.", type: "normal", status: "approved", priority: "high", riskLevel: "medium", impactAssessment: "Brief network interruption (10 seconds) during active/passive failover. All VPN tunnels will reconnect automatically.", rollbackPlan: "Revert to firmware v7.2.2 backup image stored on management server. Estimated rollback time: 15 minutes.", affectedCIs: ["FW-PROD-01", "FW-PROD-02"], assignedAgentId: changeAgent.id, approvedBy: "CAB Board" }),
    storage.createChangeRequest({ title: "Migrate Email Gateway to Cloud", description: "Phase 1 of email infrastructure modernization. Migrating on-premises email gateway to cloud-hosted solution. Includes DNS MX record changes and mail flow rule migration.", type: "major", status: "under_review", priority: "medium", riskLevel: "high", impactAssessment: "Potential email delivery delays of up to 4 hours during DNS propagation. All email rules and filters must be validated in new environment.", rollbackPlan: "Revert DNS MX records to point back to on-premises gateway. Keep old gateway active for 30 days as fallback.", affectedCIs: ["MAIL-GW-01", "DNS-PRIMARY", "DNS-SECONDARY"], assignedAgentId: changeAgent.id }),
    storage.createChangeRequest({ title: "Deploy New SIEM Correlation Rules", description: "Deploy 15 new correlation rules to the SIEM platform targeting APT detection patterns identified in latest threat intelligence feeds.", type: "standard", status: "implemented", priority: "medium", riskLevel: "low", impactAssessment: "Minimal impact. New rules may generate additional alerts during initial tuning period (est. 48 hours). False positive rate expected at 5%.", rollbackPlan: "Disable new rule set via SIEM management console. Previous rule set remains unchanged.", affectedCIs: ["SIEM-CLUSTER-01"], assignedAgentId: changeAgent.id, approvedBy: "SOC Lead", implementedBy: "Security Engineering" }),
    storage.createChangeRequest({ title: "Database Server Memory Upgrade", description: "Increase RAM from 64GB to 128GB on production database servers DB-PROD-01 and DB-PROD-02 to address connection pool exhaustion issues.", type: "normal", status: "submitted", priority: "critical", riskLevel: "medium", impactAssessment: "Requires server restart. Failover to standby database during maintenance. Application will switch to read-only mode for approximately 5 minutes per server.", rollbackPlan: "If memory modules are defective, remove new modules and restore original configuration. Server will boot with original 64GB.", affectedCIs: ["DB-PROD-01", "DB-PROD-02"], assignedAgentId: changeAgent.id }),
  ]);

  await Promise.all([
    storage.createServiceCatalogItem({ name: "New User Account Setup", description: "Create Active Directory account, email, VPN access, and role-based application access for new employees.", category: "Access Management", icon: "UserPlus", estimatedTime: "4 hours", slaTarget: "1 business day", approvalRequired: true, active: true }),
    storage.createServiceCatalogItem({ name: "Password Reset", description: "Reset password and resynchronize MFA tokens for locked or compromised accounts.", category: "Access Management", icon: "KeyRound", estimatedTime: "30 minutes", slaTarget: "1 hour", approvalRequired: false, active: true }),
    storage.createServiceCatalogItem({ name: "Software Installation Request", description: "Request installation of approved software from the corporate software catalog.", category: "Software", icon: "Download", estimatedTime: "2 hours", slaTarget: "4 hours", approvalRequired: true, active: true }),
    storage.createServiceCatalogItem({ name: "Hardware Request", description: "Request new hardware including laptops, monitors, peripherals, and mobile devices.", category: "Hardware", icon: "Monitor", estimatedTime: "3-5 business days", slaTarget: "5 business days", approvalRequired: true, active: true }),
    storage.createServiceCatalogItem({ name: "VPN Access", description: "Request or modify VPN access for remote connectivity. Includes split-tunnel and full-tunnel options.", category: "Network", icon: "Globe", estimatedTime: "2 hours", slaTarget: "4 hours", approvalRequired: true, active: true }),
    storage.createServiceCatalogItem({ name: "Email Distribution List", description: "Create or modify email distribution lists and shared mailboxes.", category: "Email", icon: "Mail", estimatedTime: "1 hour", slaTarget: "4 hours", approvalRequired: false, active: true }),
    storage.createServiceCatalogItem({ name: "Firewall Rule Change", description: "Request new firewall rules or modify existing network access policies.", category: "Security", icon: "ShieldCheck", estimatedTime: "4 hours", slaTarget: "1 business day", approvalRequired: true, active: true }),
    storage.createServiceCatalogItem({ name: "Server Provisioning", description: "Request new virtual or physical server deployment with specified configuration.", category: "Infrastructure", icon: "Server", estimatedTime: "2-3 business days", slaTarget: "3 business days", approvalRequired: true, active: true }),
  ]);

  await Promise.all([
    storage.createKnowledgeArticle({ title: "VPN Tunnel Connectivity Troubleshooting", content: "## Common VPN Issues and Solutions\n\n### Cannot Connect to VPN\n1. Verify your credentials are correct\n2. Check if your VPN client is up-to-date (current version: 4.8.2)\n3. Try the backup VPN gateway: vpn-backup.company.com\n4. Ensure ports 443 and 4433 are not blocked by your local firewall\n\n### Frequent Disconnections\n- Switch to TCP protocol in VPN client settings (Settings > Protocol > TCP)\n- Disable sleep/hibernate on your device during active VPN sessions\n- If on WiFi, try a wired connection for stability\n\n### Split Tunnel Not Working\n- Verify your VPN profile is set to 'Split Tunnel' mode\n- Check with IT if your department requires full tunnel access", category: "Networking", tags: ["vpn", "connectivity", "remote-access", "troubleshooting"], status: "published" }),
    storage.createKnowledgeArticle({ title: "MFA Setup and Recovery Procedures", content: "## Setting Up Multi-Factor Authentication\n\n### Supported MFA Methods\n- Microsoft Authenticator app (recommended)\n- Hardware FIDO2 security key\n- SMS verification (backup only)\n\n### Initial Setup\n1. Navigate to https://security.company.com/mfa\n2. Sign in with your corporate credentials\n3. Select your preferred MFA method\n4. Follow the enrollment wizard\n\n### Lost MFA Device\n1. Contact the Service Desk immediately\n2. A temporary bypass code will be issued (valid 24 hours)\n3. Re-enroll your new device within the bypass window", category: "Identity & Access", tags: ["mfa", "authentication", "security", "setup"], status: "published" }),
    storage.createKnowledgeArticle({ title: "Incident Severity Classification Guide", content: "## Severity Levels\n\n### Critical (P1)\n- Complete system outage\n- Active security breach\n- Response: 15 min | Resolution: 4 hours\n\n### High (P2)\n- Major functionality degraded\n- Response: 30 min | Resolution: 8 hours\n\n### Medium (P3)\n- Moderate impact\n- Response: 2 hours | Resolution: 24 hours\n\n### Low (P4)\n- Minor issues\n- Response: 8 hours | Resolution: 5 business days", category: "ITSM Process", tags: ["incidents", "severity", "classification", "sla"], status: "published" }),
    storage.createKnowledgeArticle({ title: "Change Management Process Overview", content: "## Change Types\n\n### Standard Changes\nPre-approved, low-risk changes. Examples: scheduled patching, pre-approved software installs.\n\n### Normal Changes\nRequire CAB (Change Advisory Board) approval. Submit via Change Request form with risk assessment and rollback plan.\n\n### Emergency Changes\nUrgent changes to resolve critical incidents. Require retrospective CAB review within 48 hours.\n\n## Workflow\nDraft → Submitted → Under Review → Approved → Scheduled → Implemented → Closed\n\n### Rollback Criteria\n- Service degradation exceeds 10% threshold\n- Unexpected dependency failures\n- User impact confirmed within first 30 minutes", category: "ITSM Process", tags: ["change-management", "itil", "cab", "process"], status: "published" }),
    storage.createKnowledgeArticle({ title: "Root Cause Analysis Methodology", content: "## Problem Management RCA Process\n\n### Step 1: Problem Identification\nCorrelate recurring incidents by category, affected CI, and time pattern.\n\n### Step 2: Root Cause Investigation\n- 5 Whys Analysis: Iteratively ask 'Why?' to drill to the root cause\n- Ishikawa (Fishbone) Diagram: Categorize causes by People, Process, Technology, Environment\n- Timeline Analysis: Map events chronologically to identify trigger points\n\n### Step 3: Known Error Record\nOnce root cause is identified, create a Known Error with:\n- Workaround steps for Service Desk\n- Affected services and CIs\n- Permanent fix plan and target date\n\n### Step 4: Resolution Verification\nConfirm fix eliminates recurrence over a 30-day monitoring window.", category: "ITSM Process", tags: ["rca", "root-cause", "problem", "known-error", "investigation"], status: "published" }),
    storage.createKnowledgeArticle({ title: "New Hire IT Provisioning Checklist", content: "## Service Request: New Employee Onboarding\n\n### Day -3 (Before Start Date)\n- [ ] Create Active Directory account\n- [ ] Assign Microsoft 365 license (E3 or E5 per department)\n- [ ] Provision email and Teams access\n- [ ] Create VPN profile\n\n### Day -1\n- [ ] Stage laptop with standard image\n- [ ] Install department-specific software\n- [ ] Configure MFA enrollment token\n- [ ] Prepare welcome packet with credentials\n\n### Day 1\n- [ ] Verify login and MFA enrollment\n- [ ] Confirm VPN connectivity from workstation\n- [ ] Grant application-specific access per manager approval\n- [ ] Close Service Request as Fulfilled", category: "Identity & Access", tags: ["onboarding", "provisioning", "new-hire", "checklist"], status: "published" }),
    storage.createKnowledgeArticle({ title: "Firewall Firmware Patching Procedure", content: "## Change Request: Firewall Firmware Update\n\n### Pre-Change Checklist\n- [ ] Backup current configuration\n- [ ] Verify HA failover is functional\n- [ ] Confirm maintenance window with NOC\n- [ ] Notify affected service owners\n\n### Patching Steps\n1. Download firmware from vendor portal (verify checksum)\n2. Upload to standby unit first\n3. Apply and reboot standby — verify services\n4. Failover traffic to patched unit\n5. Patch primary unit and reboot\n6. Restore HA active/standby roles\n\n### Rollback Plan\n- Revert to previous firmware image stored in secondary boot partition\n- Estimated rollback time: 8 minutes per unit\n\n### Post-Change Validation\n- Confirm all firewall policies are intact\n- Verify VPN tunnels re-establish\n- Check HA sync status\n- Monitor for 30 minutes before closing change", category: "Firewall", tags: ["firewall", "firmware", "patching", "maintenance-window"], status: "published" }),
    storage.createKnowledgeArticle({ title: "Database Connection Pool Exhaustion", content: "## Known Error: DB Connection Pool Saturation\n\n### Symptoms\n- Application timeouts (HTTP 504) during peak hours\n- Database logs show 'too many connections' errors\n- Connection pool utilization at 100% in monitoring\n\n### Root Cause\nDefault connection pool size (25) insufficient for current application load. Long-running queries hold connections, starving new requests.\n\n### Workaround\n1. Restart the application service to release stale connections\n2. Kill long-running queries: `SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE state = 'active' AND duration > interval '5 minutes'`\n\n### Permanent Fix\n- Increase pool size to 50 in application config\n- Implement connection timeout of 30 seconds\n- Add query execution time limit of 60 seconds\n- Scheduled for next maintenance window (Change CHG-2024-0089)", category: "Database", tags: ["database", "connection-pool", "known-error", "performance"], status: "published" }),
    storage.createKnowledgeArticle({ title: "SIEM Correlation Rule Tuning", content: "## Operational Knowledge: SIEM Rule Management\n\n### When to Tune Rules\n- False positive rate exceeds 15% for any single rule\n- Alert fatigue reported by SOC analysts\n- New infrastructure added that generates novel log patterns\n\n### Tuning Process\n1. Export last 30 days of alerts for the target rule\n2. Classify each alert: True Positive / False Positive / Benign True Positive\n3. Identify patterns in false positives (source IPs, user agents, time windows)\n4. Add exclusion filters or adjust thresholds\n5. Test in simulation mode for 48 hours before activating\n\n### Critical Rules (Never Disable)\n- Brute force detection (>10 failed logins in 5 min)\n- Privilege escalation attempts\n- Data exfiltration indicators (>500MB outbound to new destination)\n- Lateral movement detection", category: "Security", tags: ["siem", "correlation", "security-operations", "alert-tuning"], status: "published" }),
    storage.createKnowledgeArticle({ title: "SLA Breach Escalation Procedures", content: "## Service Level Agreement Breach Handling\n\n### SLA Tiers and Response\n| Priority | Response Time | Resolution Time | Escalation Path |\n|----------|--------------|-----------------|------------------|\n| Critical | 15 min | 4 hours | On-Call Manager → VP of IT |\n| High | 30 min | 8 hours | Team Lead → Department Manager |\n| Medium | 2 hours | 24 hours | Team Lead |\n| Low | 8 hours | 5 business days | Weekly Review |\n\n### At-Risk Indicators (75% of SLA elapsed)\n- Automatic notification to assigned agent and team lead\n- Priority bump consideration for stalled tickets\n- Resource reallocation if needed\n\n### Breach Actions\n1. Immediate escalation per escalation path above\n2. Root cause documentation required within 24 hours\n3. Service improvement plan if same CI breaches SLA 3+ times in 30 days\n4. Monthly SLA compliance report to management", category: "ITSM Process", tags: ["sla", "escalation", "compliance", "service-level"], status: "published" }),
  ]);

  const demoUser = await storage.getUserByUsername("demo");
  if (demoUser) {
    const bcpUserId = demoUser.id;

    await Promise.all([
      storage.createBcpPlan({ userId: bcpUserId, title: "IT Operations Continuity Plan", description: "Comprehensive plan ensuring continuity of all critical IT operations including infrastructure management, application support, and service delivery during disruptive events.", status: "active", category: "technology", businessImpactLevel: "critical", rtoHours: 4, rpoHours: 1, criticalProcesses: ["Server and infrastructure monitoring", "Help desk and incident response", "Email and communication systems", "Identity and access management", "Backup and data protection"], recoveryStrategy: "Activate secondary operations center with pre-configured workstations and VPN access. Failover monitoring systems to cloud-hosted dashboards. Engage on-call IT staff via automated notification tree. Restore critical services in priority order: authentication, email, monitoring, then application services.", stakeholders: ["VP of IT Operations", "Infrastructure Manager", "Application Support Lead", "Service Desk Manager", "CISO"], owner: "VP of IT Operations", priority: "critical" }),
      storage.createBcpPlan({ userId: bcpUserId, title: "Cybersecurity Incident Response Plan", description: "Defines procedures for detecting, containing, eradicating, and recovering from cybersecurity incidents including data breaches, ransomware attacks, and advanced persistent threats.", status: "active", category: "technology", businessImpactLevel: "critical", rtoHours: 2, rpoHours: 0, criticalProcesses: ["Threat detection and SIEM monitoring", "Incident triage and classification", "Forensic evidence preservation", "Malware containment and eradication", "Regulatory breach notification"], recoveryStrategy: "Activate CSIRT team immediately upon detection. Isolate affected systems using network segmentation. Preserve forensic evidence before remediation. Deploy pre-built clean images for compromised endpoints. Restore from last known-good backups verified against IOC signatures. Conduct post-incident review within 48 hours.", stakeholders: ["CISO", "SOC Manager", "Legal Counsel", "VP of IT Operations", "Communications Director", "Compliance Officer"], owner: "CISO", priority: "critical" }),
      storage.createBcpPlan({ userId: bcpUserId, title: "Data Center Failover Plan", description: "Ensures seamless failover of all data center operations from primary DC-1 to secondary DC-2 facility in the event of catastrophic failure, natural disaster, or extended power outage.", status: "approved", category: "facilities", businessImpactLevel: "critical", rtoHours: 1, rpoHours: 0, criticalProcesses: ["Power and cooling systems management", "Network connectivity and routing", "Storage replication and synchronization", "Compute resource provisioning", "Physical security and access control"], recoveryStrategy: "Automated failover triggers when primary DC health checks fail for 3 consecutive intervals. DNS and BGP routing automatically redirect to DC-2. Synchronous replication ensures zero data loss for Tier-1 applications. Asynchronous replication for Tier-2 with RPO under 15 minutes. Facilities team dispatched to assess primary DC within 2 hours.", stakeholders: ["Infrastructure Director", "Network Operations Manager", "Facilities Manager", "VP of IT Operations", "Storage Administrator"], owner: "Infrastructure Director", priority: "critical" }),
      storage.createBcpPlan({ userId: bcpUserId, title: "Remote Workforce Continuity Plan", description: "Maintains business operations when employees cannot access physical offices due to pandemic, severe weather, civil disruption, or facilities damage. Covers remote access, collaboration tools, and workforce management.", status: "active", category: "personnel", businessImpactLevel: "high", rtoHours: 8, rpoHours: 4, criticalProcesses: ["VPN and remote access provisioning", "Cloud collaboration platform availability", "Virtual desktop infrastructure", "Employee communication and wellness checks", "Payroll and HR system access"], recoveryStrategy: "Activate mass notification system to inform all employees. Scale VPN gateway capacity to handle 100% remote workforce. Enable emergency cloud desktop provisioning for employees without company devices. Establish daily virtual check-ins through team leads. Deploy temporary hotspot devices to employees in areas with poor connectivity.", stakeholders: ["HR Director", "IT Service Desk Manager", "VP of IT Operations", "Facilities Manager", "Department Heads"], owner: "HR Director", priority: "high" }),
      storage.createBcpPlan({ userId: bcpUserId, title: "Critical Application Recovery Plan", description: "Covers recovery procedures for mission-critical business applications including ERP, CRM, financial systems, and customer-facing platforms to minimize business impact during outages.", status: "under_review", category: "technology", businessImpactLevel: "high", rtoHours: 4, rpoHours: 2, criticalProcesses: ["ERP system operations", "CRM and customer data access", "Financial transaction processing", "Customer portal and e-commerce", "API gateway and integration services"], recoveryStrategy: "Prioritize application recovery based on BIA tier classification. Tier-1 applications restored from hot standby within 1 hour. Tier-2 applications recovered from warm standby within 4 hours. Database point-in-time recovery using transaction log shipping. Application teams validate functionality using automated smoke test suites before declaring service restored.", stakeholders: ["Application Manager", "Database Administrator", "QA Lead", "Business Unit Owners", "VP of IT Operations"], owner: "Application Manager", priority: "high" }),
    ]);

    await Promise.all([
      storage.createDrpPlan({ userId: bcpUserId, title: "Primary Data Center DR Plan", description: "Disaster recovery plan for complete primary data center failure. Covers automatic failover to secondary site with real-time replication and zero data loss for critical workloads.", status: "active", disasterType: "hardware_failure", severity: "critical", rtoHours: 1, rpoHours: 0, affectedSystems: ["Core network switches", "Production database cluster", "Application servers", "Storage area network", "Virtualization platform"], recoveryProcedures: "1. Automated health monitoring detects DC-1 failure.\n2. Orchestration platform triggers failover sequence.\n3. DNS and BGP routing updated to DC-2 endpoints.\n4. Storage arrays promote replicated volumes to primary.\n5. Virtual machines restart on DC-2 hypervisors using replicated state.\n6. Load balancers redirect traffic to DC-2 application tier.\n7. Monitoring systems verify all services operational.\n8. Notify stakeholders of failover completion.", failoverType: "automatic", failoverTarget: "DC-2 Secondary Data Center", backupLocation: "DC-2 Rack B1-B4 with synchronized storage arrays", testResult: "passed", owner: "Infrastructure Director" }),
      storage.createDrpPlan({ userId: bcpUserId, title: "Ransomware Recovery Plan", description: "Comprehensive recovery procedures for ransomware attacks including system isolation, clean restoration from immutable backups, and forensic investigation protocols.", status: "active", disasterType: "cyber_attack", severity: "critical", rtoHours: 4, rpoHours: 1, affectedSystems: ["Windows domain controllers", "File servers and NAS", "Email infrastructure", "Endpoint workstations", "Active Directory services"], recoveryProcedures: "1. Immediately isolate affected network segments at switch level.\n2. Disable compromised user accounts in Active Directory.\n3. Activate CSIRT and begin forensic evidence collection.\n4. Identify ransomware variant and infection vector.\n5. Restore domain controllers from offline immutable backups.\n6. Rebuild file servers using clean OS images and restore data.\n7. Deploy updated endpoint protection signatures.\n8. Reconnect segments incrementally with enhanced monitoring.\n9. Conduct user credential reset across all affected accounts.", failoverType: "manual", failoverTarget: "Air-gapped recovery environment", backupLocation: "Immutable backup vault (AWS S3 Object Lock) with 90-day retention", testResult: "passed", owner: "CISO" }),
      storage.createDrpPlan({ userId: bcpUserId, title: "Network Infrastructure DR Plan", description: "Recovery plan for major network infrastructure failures including core switching, routing, WAN links, and firewall systems affecting enterprise connectivity.", status: "approved", disasterType: "network_failure", severity: "high", rtoHours: 2, rpoHours: 1, affectedSystems: ["Core and distribution switches", "WAN/MPLS circuits", "Firewall clusters", "Load balancers", "DNS infrastructure"], recoveryProcedures: "1. Network monitoring detects connectivity loss on primary paths.\n2. Automated BGP failover engages backup ISP circuits.\n3. OSPF reconverges around failed network segments.\n4. Firewall cluster fails over to standby unit.\n5. Load balancers redistribute traffic to available servers.\n6. DNS TTL settings enable rapid failover (60-second TTL).\n7. NOC team validates connectivity from all major sites.\n8. Vendor support engaged for hardware replacement if needed.", failoverType: "semi_automatic", failoverTarget: "Redundant network paths via backup ISP", backupLocation: "Network configuration backups stored in version-controlled repository", testResult: "partial", owner: "Network Operations Manager" }),
      storage.createDrpPlan({ userId: bcpUserId, title: "Database Disaster Recovery Plan", description: "Ensures rapid recovery of all production databases with zero data loss using synchronous replication, automated failover, and point-in-time recovery capabilities.", status: "active", disasterType: "data_breach", severity: "critical", rtoHours: 2, rpoHours: 0, affectedSystems: ["PostgreSQL production clusters", "Redis cache layer", "Elasticsearch indices", "Data warehouse", "Reporting databases"], recoveryProcedures: "1. Database monitoring detects primary failure or corruption.\n2. Automated failover promotes synchronous replica to primary.\n3. Application connection strings updated via service discovery.\n4. Point-in-time recovery initiated if data corruption detected.\n5. Transaction log replay to recover to last consistent state.\n6. Data integrity checks run across all recovered databases.\n7. Cache layer rebuilt from recovered database state.\n8. Search indices rebuilt from primary data sources.\n9. Stakeholders notified of recovery status and any data gaps.", failoverType: "automatic", failoverTarget: "Synchronous database replica in DC-2", backupLocation: "Continuous WAL archiving to S3 with 30-day retention and daily snapshots", testResult: "passed", owner: "Database Administrator" }),
      storage.createDrpPlan({ userId: bcpUserId, title: "Cloud Service Failover Plan", description: "Disaster recovery plan for cloud-hosted services including IaaS, PaaS, and SaaS components. Covers multi-region failover and cloud provider outage scenarios.", status: "under_review", disasterType: "hardware_failure", severity: "high", rtoHours: 1, rpoHours: 0, affectedSystems: ["AWS EC2 instances", "RDS database services", "S3 storage buckets", "Lambda functions", "CloudFront CDN"], recoveryProcedures: "1. CloudWatch alarms detect regional service degradation.\n2. Route 53 health checks trigger DNS failover to secondary region.\n3. Cross-region RDS read replica promoted to primary.\n4. EC2 Auto Scaling groups launch instances in failover region.\n5. S3 cross-region replication ensures data availability.\n6. Lambda functions deployed in secondary region via CI/CD.\n7. CDN origin updated to secondary region endpoints.\n8. Synthetic monitoring validates application health in failover region.", failoverType: "automatic", failoverTarget: "AWS us-west-2 (Oregon) secondary region", backupLocation: "Cross-region replication to us-west-2 with S3 versioning enabled", testResult: "not_tested", owner: "Cloud Architect" }),
      storage.createDrpPlan({ userId: bcpUserId, title: "Communication Systems DR Plan", description: "Recovery plan for enterprise communication systems including email, VoIP, unified communications, and emergency notification systems during extended outages.", status: "draft", disasterType: "power_outage", severity: "medium", rtoHours: 4, rpoHours: 2, affectedSystems: ["Email gateway and mailboxes", "VoIP PBX system", "Microsoft Teams platform", "Emergency mass notification", "Contact center infrastructure"], recoveryProcedures: "1. Activate backup power systems for communication infrastructure.\n2. Verify email failover to cloud-hosted backup MX records.\n3. Redirect VoIP traffic to SIP trunking backup provider.\n4. Confirm Microsoft Teams cloud services operational.\n5. Test emergency mass notification system from backup site.\n6. Enable call forwarding for contact center to mobile agents.\n7. Deploy satellite communication kits if terrestrial links unavailable.\n8. Establish hourly status updates via backup communication channels.", failoverType: "manual", failoverTarget: "Cloud-hosted communication backup (Microsoft 365)", backupLocation: "Email archives in Exchange Online with 7-year retention policy", testResult: "not_tested", owner: "Communications Manager" }),
    ]);
  }

  await Promise.all([
    storage.createSlaDefinition({ name: "Critical Priority SLA", description: "For system-wide outages and active security breaches.", priority: "critical", responseTimeMinutes: 15, resolutionTimeMinutes: 240, escalationPolicy: "Auto-escalate to On-Call Manager after 10 minutes. Notify VP of IT after 30 minutes.", active: true }),
    storage.createSlaDefinition({ name: "High Priority SLA", description: "For major service degradation and security vulnerabilities.", priority: "high", responseTimeMinutes: 30, resolutionTimeMinutes: 480, escalationPolicy: "Auto-escalate to Team Lead after 20 minutes.", active: true }),
    storage.createSlaDefinition({ name: "Medium Priority SLA", description: "For moderate impact issues affecting departments.", priority: "medium", responseTimeMinutes: 120, resolutionTimeMinutes: 1440, escalationPolicy: "Auto-escalate to Team Lead after 1 hour.", active: true }),
    storage.createSlaDefinition({ name: "Low Priority SLA", description: "For minor issues and feature requests.", priority: "low", responseTimeMinutes: 480, resolutionTimeMinutes: 7200, escalationPolicy: "Weekly review by Service Desk lead.", active: true }),
  ]);

  const cmdbItemsCreated = await Promise.all([
    storage.createCmdbItem({ name: "FW-PROD-01", type: "Firewall", category: "hardware", status: "active", environment: "production", owner: "Network Operations", location: "DC-1 Rack A3", ipAddress: "10.0.0.1", osVersion: "FortiOS v7.2.2", manufacturer: "Fortinet", model: "FortiGate 600E", serialNumber: "FG6E-SN-7834921", firmware: "v7.2.2-build1334" }),
    storage.createCmdbItem({ name: "FW-PROD-02", type: "Firewall", category: "hardware", status: "active", environment: "production", owner: "Network Operations", location: "DC-2 Rack A3", ipAddress: "10.0.0.2", osVersion: "FortiOS v7.2.2", manufacturer: "Fortinet", model: "FortiGate 600E", serialNumber: "FG6E-SN-7834922", firmware: "v7.2.2-build1334" }),
    storage.createCmdbItem({ name: "DB-PROD-01", type: "Database Server", category: "hardware", status: "active", environment: "production", owner: "Database Administration", location: "DC-1 Rack B2", ipAddress: "10.1.2.10", osVersion: "Ubuntu 22.04 LTS", manufacturer: "Dell", model: "PowerEdge R750", serialNumber: "DL-PE-R750-44821", firmware: "BIOS 2.14.1" }),
    storage.createCmdbItem({ name: "DB-PROD-02", type: "Database Server", category: "hardware", status: "active", environment: "production", owner: "Database Administration", location: "DC-2 Rack B2", ipAddress: "10.1.2.11", osVersion: "Ubuntu 22.04 LTS", manufacturer: "Dell", model: "PowerEdge R750", serialNumber: "DL-PE-R750-44822", firmware: "BIOS 2.14.1" }),
    storage.createCmdbItem({ name: "MAIL-GW-01", type: "Mail Gateway", category: "hardware", status: "active", environment: "production", owner: "Messaging Team", location: "DC-1 Rack C1", ipAddress: "10.2.0.5", osVersion: "Barracuda OS v8.1", manufacturer: "Barracuda", model: "Email Security 600", serialNumber: "BR-ES600-99213" }),
    storage.createCmdbItem({ name: "SIEM-CLUSTER-01", type: "SIEM Platform", category: "software", status: "active", environment: "production", owner: "SOC", location: "DC-1 Rack D1-D3", ipAddress: "10.3.0.10", osVersion: "Splunk Enterprise 9.2", manufacturer: "Splunk", model: "Enterprise", serialNumber: "SPL-ENT-LIC-2026" }),
    storage.createCmdbItem({ name: "APP-WEB-01", type: "Web Server", category: "hardware", status: "active", environment: "production", owner: "Application Support", location: "DC-1 Rack E1", ipAddress: "10.4.0.20", osVersion: "RHEL 9.2", manufacturer: "HP", model: "ProLiant DL380 Gen10", serialNumber: "HP-DL380-67123" }),
    storage.createCmdbItem({ name: "VPN-PRIMARY", type: "VPN Gateway", category: "hardware", status: "active", environment: "production", owner: "Network Operations", location: "DC-1 Rack A1", ipAddress: "10.0.1.1", osVersion: "Cisco AnyConnect v4.10", manufacturer: "Cisco", model: "ASA 5585-X", serialNumber: "CS-ASA5585-33901" }),
    storage.createCmdbItem({ name: "DNS-PRIMARY", type: "DNS Server", category: "software", status: "active", environment: "production", owner: "Network Operations", location: "DC-1 Rack F1", ipAddress: "10.0.0.53", osVersion: "BIND 9.18", manufacturer: "Dell", model: "PowerEdge R640", serialNumber: "DL-PE-R640-22341" }),
    storage.createCmdbItem({ name: "BACKUP-SRV-01", type: "Backup Server", category: "hardware", status: "active", environment: "production", owner: "Storage Team", location: "DC-2 Rack G1", ipAddress: "10.5.0.10", osVersion: "Veeam B&R v12", manufacturer: "Dell", model: "PowerEdge R740", serialNumber: "DL-PE-R740-88912" }),
    storage.createCmdbItem({ name: "CORE-SW-01", type: "Network Switch", category: "hardware", status: "active", environment: "production", owner: "Network Operations", location: "DC-1 Rack A1", ipAddress: "10.0.0.100", osVersion: "Cisco IOS XE 17.9", manufacturer: "Cisco", model: "Catalyst 9300-48P", serialNumber: "CS-C9300-44501", firmware: "17.09.04a" }),
    storage.createCmdbItem({ name: "CORE-SW-02", type: "Network Switch", category: "hardware", status: "active", environment: "production", owner: "Network Operations", location: "DC-2 Rack A1", ipAddress: "10.0.0.101", osVersion: "Cisco IOS XE 17.9", manufacturer: "Cisco", model: "Catalyst 9300-48P", serialNumber: "CS-C9300-44502", firmware: "17.09.04a" }),
    storage.createCmdbItem({ name: "AP-FLOOR3-01", type: "Wireless AP", category: "hardware", status: "active", environment: "production", owner: "Network Operations", location: "Building A Floor 3", ipAddress: "10.10.3.1", osVersion: "Meraki MR56", manufacturer: "Cisco Meraki", model: "MR56", serialNumber: "MR-56-Q8844" }),
    storage.createCmdbItem({ name: "UPS-DC1-01", type: "UPS", category: "hardware", status: "active", environment: "production", owner: "Facilities", location: "DC-1 Power Room", ipAddress: "10.0.0.200", manufacturer: "APC", model: "Smart-UPS SRT 10000VA", serialNumber: "APC-SRT10K-77231" }),
    storage.createCmdbItem({ name: "HVAC-DC1-01", type: "HVAC Controller", category: "iot", status: "active", environment: "production", owner: "Facilities", location: "DC-1 Cooling", ipAddress: "10.20.0.1", manufacturer: "Schneider Electric", model: "EcoStruxure IT", serialNumber: "SE-ECO-33211", firmware: "v3.4.1" }),
    storage.createCmdbItem({ name: "TEMP-SENSOR-01", type: "Temperature Sensor", category: "iot", status: "active", environment: "production", owner: "Facilities", location: "DC-1 Server Room A", ipAddress: "10.20.1.10", manufacturer: "Paessler", model: "PRTG Environment", serialNumber: "PR-ENV-88421", firmware: "v2.1.0" }),
    storage.createCmdbItem({ name: "TEMP-SENSOR-02", type: "Temperature Sensor", category: "iot", status: "active", environment: "production", owner: "Facilities", location: "DC-1 Server Room B", ipAddress: "10.20.1.11", manufacturer: "Paessler", model: "PRTG Environment", serialNumber: "PR-ENV-88422", firmware: "v2.1.0" }),
    storage.createCmdbItem({ name: "DOOR-CTRL-01", type: "Access Controller", category: "iot", status: "active", environment: "production", owner: "Physical Security", location: "DC-1 Main Entrance", ipAddress: "10.20.2.1", manufacturer: "HID Global", model: "VertX V2000", serialNumber: "HID-V2K-55712", firmware: "v4.3.2" }),
    storage.createCmdbItem({ name: "CAM-DC1-01", type: "IP Camera", category: "iot", status: "active", environment: "production", owner: "Physical Security", location: "DC-1 Entrance", ipAddress: "10.20.3.1", manufacturer: "Axis", model: "P3245-V", serialNumber: "AX-P3245-99123", firmware: "11.4.62" }),
    storage.createCmdbItem({ name: "PDU-DC1-R01", type: "Smart PDU", category: "iot", status: "active", environment: "production", owner: "Facilities", location: "DC-1 Rack A1", ipAddress: "10.20.4.1", manufacturer: "Raritan", model: "PX3-5902V", serialNumber: "RAR-PX3-44821", firmware: "v3.8.1" }),
    storage.createCmdbItem({ name: "K8S-MASTER-01", type: "Container Platform", category: "software", status: "active", environment: "production", owner: "DevOps", location: "DC-1 Virtual", ipAddress: "10.6.0.10", osVersion: "Kubernetes v1.29.2", manufacturer: "Red Hat", model: "OpenShift 4.14" }),
    storage.createCmdbItem({ name: "MQTT-BROKER-01", type: "Message Broker", category: "software", status: "active", environment: "production", owner: "IoT Team", location: "DC-1 Virtual", ipAddress: "10.20.0.50", osVersion: "Eclipse Mosquitto 2.0.18", manufacturer: "Eclipse Foundation", model: "Mosquitto" }),
    storage.createCmdbItem({ name: "PROXY-01", type: "Reverse Proxy", category: "software", status: "active", environment: "production", owner: "Web Operations", location: "DC-1 Rack E2", ipAddress: "10.4.0.1", osVersion: "NGINX Plus R31", manufacturer: "F5", model: "NGINX Plus" }),
    storage.createCmdbItem({ name: "LOG-COLLECTOR-01", type: "Syslog Server", category: "software", status: "active", environment: "production", owner: "SOC", location: "DC-1 Virtual", ipAddress: "10.3.0.20", osVersion: "Graylog 5.2", manufacturer: "Graylog Inc", model: "Enterprise" }),
    storage.createCmdbItem({ name: "WH-SENSOR-MESH", type: "Sensor Mesh", category: "iot", status: "active", environment: "production", owner: "Warehouse Ops", location: "Warehouse Zone A-D", ipAddress: "10.30.0.0/24", manufacturer: "Particle", model: "Argon Mesh", serialNumber: "PART-MESH-001", firmware: "Device OS 5.6.0" }),
  ]);

  await Promise.all([
    storage.createCmdbRelationship({ sourceItemId: cmdbItemsCreated[0].id, targetItemId: cmdbItemsCreated[1].id, relationshipType: "failover_pair" }),
    storage.createCmdbRelationship({ sourceItemId: cmdbItemsCreated[2].id, targetItemId: cmdbItemsCreated[3].id, relationshipType: "replication_pair" }),
    storage.createCmdbRelationship({ sourceItemId: cmdbItemsCreated[6].id, targetItemId: cmdbItemsCreated[2].id, relationshipType: "depends_on" }),
    storage.createCmdbRelationship({ sourceItemId: cmdbItemsCreated[6].id, targetItemId: cmdbItemsCreated[0].id, relationshipType: "protected_by" }),
    storage.createCmdbRelationship({ sourceItemId: cmdbItemsCreated[5].id, targetItemId: cmdbItemsCreated[23].id, relationshipType: "depends_on" }),
    storage.createCmdbRelationship({ sourceItemId: cmdbItemsCreated[10].id, targetItemId: cmdbItemsCreated[11].id, relationshipType: "redundant_with" }),
    storage.createCmdbRelationship({ sourceItemId: cmdbItemsCreated[14].id, targetItemId: cmdbItemsCreated[15].id, relationshipType: "controls" }),
    storage.createCmdbRelationship({ sourceItemId: cmdbItemsCreated[14].id, targetItemId: cmdbItemsCreated[16].id, relationshipType: "controls" }),
    storage.createCmdbRelationship({ sourceItemId: cmdbItemsCreated[21].id, targetItemId: cmdbItemsCreated[24].id, relationshipType: "connects_to" }),
    storage.createCmdbRelationship({ sourceItemId: cmdbItemsCreated[13].id, targetItemId: cmdbItemsCreated[19].id, relationshipType: "powers" }),
    storage.createCmdbRelationship({ sourceItemId: cmdbItemsCreated[20].id, targetItemId: cmdbItemsCreated[6].id, relationshipType: "hosts" }),
  ]);

  const connectors = await Promise.all([
    storage.createConnector({ name: "DC-1 Core Network SNMP", protocol: "snmp", host: "10.0.0.0/24", port: 161, status: "active", credentialType: "snmp_v3", credentialRef: "vault://snmp/dc1-core", scanInterval: 5, discoveredAssets: 18, agentId: networkAgent.id, metadata: { community: "sentinel_ro", version: "v3", authProtocol: "SHA-256", privProtocol: "AES-256" } }),
    storage.createConnector({ name: "Linux Server Fleet SSH", protocol: "ssh", host: "10.1.0.0/16", port: 22, status: "active", credentialType: "ssh_key", credentialRef: "vault://ssh/linux-fleet-key", scanInterval: 15, discoveredAssets: 42, agentId: networkAgent.id, metadata: { keyType: "ed25519", jumpHost: "bastion.internal.corp", sudoEnabled: true } }),
    storage.createConnector({ name: "Windows Domain WMI", protocol: "wmi", host: "10.2.0.0/16", port: 135, status: "active", credentialType: "domain_credential", credentialRef: "vault://wmi/domain-admin", scanInterval: 30, discoveredAssets: 156, agentId: assetAgent.id, metadata: { domain: "CORP.INTERNAL", namespace: "root\\cimv2", serviceAccount: "svc_sentinel_wmi" } }),
    storage.createConnector({ name: "Cloud Infrastructure API", protocol: "rest_api", host: "api.aws.amazon.com", port: 443, status: "active", credentialType: "api_key", credentialRef: "vault://cloud/aws-sentinel-key", scanInterval: 10, discoveredAssets: 89, agentId: assetAgent.id, metadata: { provider: "AWS", regions: ["us-east-1", "us-west-2", "eu-west-1"], services: ["EC2", "RDS", "Lambda", "S3", "EKS"] } }),
    storage.createConnector({ name: "IoT Sensor Network MQTT", protocol: "mqtt", host: "10.20.0.50", port: 1883, status: "active", credentialType: "tls_certificate", credentialRef: "vault://mqtt/iot-broker-cert", scanInterval: 1, discoveredAssets: 247, agentId: iotAgent.id, metadata: { broker: "Eclipse Mosquitto", topics: ["sensors/#", "actuators/#", "alerts/#"], qos: 1, retainMessages: true } }),
    storage.createConnector({ name: "Syslog Collector", protocol: "syslog", host: "10.3.0.20", port: 514, status: "active", credentialType: "tls_certificate", credentialRef: "vault://syslog/collector-cert", scanInterval: 0, discoveredAssets: 0, agentId: securityAgent.id, metadata: { protocol: "RFC5424", transport: "TLS", facility: ["auth", "authpriv", "daemon", "kern", "local0-7"], sourcesIngesting: 312 } }),
    storage.createConnector({ name: "VMware vCenter REST API", protocol: "rest_api", host: "vcenter.internal.corp", port: 443, status: "active", credentialType: "api_token", credentialRef: "vault://vmware/vcenter-token", scanInterval: 15, discoveredAssets: 64, agentId: assetAgent.id, metadata: { version: "8.0U2", datacenters: ["DC-1", "DC-2"], clusters: 4, totalVMs: 64 } }),
    storage.createConnector({ name: "Kubernetes Cluster API", protocol: "rest_api", host: "10.6.0.10", port: 6443, status: "active", credentialType: "service_account", credentialRef: "vault://k8s/sentinel-sa-token", scanInterval: 5, discoveredAssets: 128, agentId: automationAgent.id, metadata: { version: "v1.29.2", namespaces: 12, pods: 128, services: 34 } }),
    storage.createConnector({ name: "Azure AD Graph API", protocol: "rest_api", host: "graph.microsoft.com", port: 443, status: "active", credentialType: "oauth2", credentialRef: "vault://azure/sentinel-app-reg", scanInterval: 60, discoveredAssets: 2847, agentId: complianceAgent.id, metadata: { tenantId: "a]b2c-xxx", scopes: ["User.Read.All", "Device.Read.All", "AuditLog.Read.All"], managedUsers: 2847 } }),
    storage.createConnector({ name: "NetFlow Collector", protocol: "netflow", host: "10.3.0.30", port: 2055, status: "active", credentialType: "none", credentialRef: null, scanInterval: 0, discoveredAssets: 0, agentId: networkAgent.id, metadata: { version: "NetFlow v9", samplingRate: "1:100", sourceSwitches: 8, avgFlowsPerSec: 45000 } }),
  ]);

  const playbooks = await Promise.all([
    storage.createPlaybook({ name: "Auto-Restart Failed Services", description: "Detects crashed or unresponsive services via health checks and automatically restarts them. Validates service health post-restart and escalates if restart fails.", triggerType: "event", triggerCondition: "Service health check returns unhealthy for >2 consecutive checks", actions: [{ step: 1, action: "SSH connect to target host", timeout: 10 }, { step: 2, action: "Check service status via systemctl", timeout: 5 }, { step: 3, action: "Attempt graceful restart", timeout: 30 }, { step: 4, action: "Validate health endpoint returns 200", timeout: 15 }, { step: 5, action: "If failed, force restart and notify", timeout: 30 }], agentId: automationAgent.id, enabled: true, category: "remediation", severity: "high", executionCount: 47 }),
    storage.createPlaybook({ name: "Disk Space Auto-Cleanup", description: "Triggers when disk usage exceeds 85%. Cleans old logs, temp files, and rotates application logs. Extends volume if cleanup insufficient.", triggerType: "threshold", triggerCondition: "Disk usage > 85% on monitored volumes", actions: [{ step: 1, action: "Identify largest directories", timeout: 10 }, { step: 2, action: "Rotate and compress logs older than 7 days", timeout: 60 }, { step: 3, action: "Clear /tmp and application caches", timeout: 30 }, { step: 4, action: "If still >80%, extend volume by 20%", timeout: 120 }, { step: 5, action: "Report cleanup results", timeout: 5 }], agentId: automationAgent.id, enabled: true, category: "maintenance", severity: "medium", executionCount: 23 }),
    storage.createPlaybook({ name: "Brute Force IP Block", description: "Detects brute force SSH/RDP attempts and automatically blocks the source IP at the firewall level. Logs the action and creates a security incident.", triggerType: "event", triggerCondition: "More than 10 failed auth attempts from same IP in 5 minutes", actions: [{ step: 1, action: "Verify IP is not whitelisted", timeout: 5 }, { step: 2, action: "Add IP to firewall blocklist via API", timeout: 10 }, { step: 3, action: "Create security incident", timeout: 5 }, { step: 4, action: "Send notification to SOC channel", timeout: 5 }, { step: 5, action: "Schedule auto-unblock after 24 hours", timeout: 5 }], agentId: securityAgent.id, enabled: true, category: "security", severity: "critical", executionCount: 156 }),
    storage.createPlaybook({ name: "Certificate Auto-Renewal", description: "Monitors SSL/TLS certificates and automatically renews them 30 days before expiry using ACME protocol. Validates new cert and deploys to services.", triggerType: "scheduled", triggerCondition: "Daily check: certificates expiring within 30 days", actions: [{ step: 1, action: "Scan all managed certificates", timeout: 30 }, { step: 2, action: "Initiate ACME challenge for expiring certs", timeout: 60 }, { step: 3, action: "Validate new certificate chain", timeout: 15 }, { step: 4, action: "Deploy cert to load balancer and web servers", timeout: 30 }, { step: 5, action: "Verify HTTPS endpoints respond correctly", timeout: 20 }], agentId: automationAgent.id, enabled: true, category: "maintenance", severity: "medium", executionCount: 12 }),
    storage.createPlaybook({ name: "IoT Firmware Update Rollout", description: "Manages staged firmware rollouts to IoT devices. Updates 10% first (canary), monitors for issues, then rolls out to remaining devices.", triggerType: "scheduled", triggerCondition: "New firmware version available in repository", actions: [{ step: 1, action: "Validate firmware checksum and signature", timeout: 10 }, { step: 2, action: "Deploy to 10% canary group", timeout: 120 }, { step: 3, action: "Monitor canary devices for 1 hour", timeout: 3600 }, { step: 4, action: "If healthy, deploy to remaining 90%", timeout: 600 }, { step: 5, action: "Verify all devices reporting new version", timeout: 60 }], agentId: iotAgent.id, enabled: true, category: "maintenance", severity: "medium", executionCount: 8 }),
    storage.createPlaybook({ name: "Network Failover Automation", description: "Detects network path failures and automatically fails over to redundant paths. Updates routing tables and notifies network operations.", triggerType: "event", triggerCondition: "Primary network path latency >200ms or packet loss >5%", actions: [{ step: 1, action: "Verify primary path degradation", timeout: 10 }, { step: 2, action: "Activate standby path", timeout: 5 }, { step: 3, action: "Update routing tables via SNMP SET", timeout: 15 }, { step: 4, action: "Verify traffic flowing on new path", timeout: 10 }, { step: 5, action: "Create incident and schedule primary path investigation", timeout: 5 }], agentId: networkAgent.id, enabled: true, category: "remediation", severity: "critical", executionCount: 19 }),
    storage.createPlaybook({ name: "Compliance Drift Remediation", description: "Detects configuration drift from compliance baselines and auto-corrects settings. Supports CIS benchmarks, SOC2, and internal policies.", triggerType: "scheduled", triggerCondition: "Every 4 hours: scan infrastructure against compliance baselines", actions: [{ step: 1, action: "Run compliance scan against CIS benchmarks", timeout: 300 }, { step: 2, action: "Identify drifted configurations", timeout: 30 }, { step: 3, action: "Apply corrective configurations via SSH/WMI", timeout: 120 }, { step: 4, action: "Re-scan to verify compliance", timeout: 300 }, { step: 5, action: "Generate compliance report", timeout: 30 }], agentId: complianceAgent.id, enabled: true, category: "compliance", severity: "high", executionCount: 34 }),
    storage.createPlaybook({ name: "Auto-Scale Kubernetes Workloads", description: "Monitors container resource utilization and automatically scales pods horizontally when CPU/memory thresholds are breached.", triggerType: "threshold", triggerCondition: "Pod CPU >70% or Memory >80% for >5 minutes", actions: [{ step: 1, action: "Query Kubernetes metrics API", timeout: 10 }, { step: 2, action: "Calculate optimal replica count", timeout: 5 }, { step: 3, action: "Apply horizontal pod autoscaler update", timeout: 15 }, { step: 4, action: "Wait for new pods to be ready", timeout: 120 }, { step: 5, action: "Verify load distribution", timeout: 30 }], agentId: automationAgent.id, enabled: true, category: "scaling", severity: "medium", executionCount: 89 }),
    storage.createPlaybook({ name: "Patch Tuesday Auto-Deploy", description: "Automatically evaluates, tests, and deploys security patches on Patch Tuesday. Staged rollout: dev > staging > production with validation gates.", triggerType: "scheduled", triggerCondition: "Second Tuesday of each month at 02:00 UTC", actions: [{ step: 1, action: "Download and catalog available patches", timeout: 60 }, { step: 2, action: "Assess CVE severity and applicability", timeout: 30 }, { step: 3, action: "Deploy to dev environment and run tests", timeout: 3600 }, { step: 4, action: "Deploy to staging with smoke tests", timeout: 1800 }, { step: 5, action: "Schedule production deployment window", timeout: 10 }], agentId: patchAgent.id, enabled: true, category: "patching", severity: "high", executionCount: 6 }),
    storage.createPlaybook({ name: "Anomalous Traffic Isolation", description: "Detects anomalous network traffic patterns using baseline analysis and automatically isolates the affected host to prevent lateral movement.", triggerType: "event", triggerCondition: "Network traffic deviation >3 standard deviations from baseline", actions: [{ step: 1, action: "Capture traffic sample for analysis", timeout: 30 }, { step: 2, action: "Move host to quarantine VLAN via SNMP", timeout: 10 }, { step: 3, action: "Block host at firewall perimeter", timeout: 5 }, { step: 4, action: "Create critical security incident", timeout: 5 }, { step: 5, action: "Initiate forensic data collection", timeout: 120 }], agentId: securityAgent.id, enabled: true, category: "security", severity: "critical", executionCount: 7 }),
  ]);

  const now = new Date();
  await Promise.all([
    storage.createPlaybookExecution({ playbookId: playbooks[0].id, agentId: automationAgent.id, status: "completed", triggerReason: "Nginx service health check failed on APP-WEB-01 - 3 consecutive failures detected", actionsTaken: [{ step: 1, result: "Connected to 10.4.0.20 via SSH" }, { step: 2, result: "nginx.service: inactive (dead)" }, { step: 3, result: "Service restarted successfully" }, { step: 4, result: "Health endpoint returned 200 OK" }], result: "Service restored. Downtime: 47 seconds. Root cause: OOM killer triggered by memory leak in upstream module.", targetAsset: "APP-WEB-01" }),
    storage.createPlaybookExecution({ playbookId: playbooks[2].id, agentId: securityAgent.id, status: "completed", triggerReason: "847 failed SSH attempts from 192.168.45.102 in 30 minutes targeting DB-PROD-01", actionsTaken: [{ step: 1, result: "IP not in whitelist" }, { step: 2, result: "Added to FW-PROD-01 blocklist rule FW-BLK-4421" }, { step: 3, result: "Incident INC-0078 created with critical severity" }, { step: 4, result: "SOC Slack channel notified" }, { step: 5, result: "Auto-unblock scheduled for 2026-03-04 14:32 UTC" }], result: "Threat neutralized. IP 192.168.45.102 blocked at perimeter. GeoIP: Unknown VPN exit node.", targetAsset: "FW-PROD-01" }),
    storage.createPlaybookExecution({ playbookId: playbooks[1].id, agentId: automationAgent.id, status: "completed", triggerReason: "Disk usage on LOG-COLLECTOR-01 reached 91% on /var/log volume", actionsTaken: [{ step: 1, result: "/var/log/syslog: 12GB, /var/log/nginx: 8GB, /var/log/audit: 6GB" }, { step: 2, result: "Compressed 847 log files, freed 18.3GB" }, { step: 3, result: "Cleared 2.1GB from /tmp" }], result: "Disk usage reduced from 91% to 52%. No volume extension needed.", targetAsset: "LOG-COLLECTOR-01" }),
    storage.createPlaybookExecution({ playbookId: playbooks[5].id, agentId: networkAgent.id, status: "completed", triggerReason: "Primary WAN link latency spike to 340ms with 8% packet loss", actionsTaken: [{ step: 1, result: "Confirmed: primary path 340ms avg, 8.2% loss" }, { step: 2, result: "Standby path activated: 12ms latency, 0% loss" }, { step: 3, result: "BGP routing updated, convergence in 3.2 seconds" }, { step: 4, result: "All traffic verified on backup path" }, { step: 5, result: "Incident INC-NET-0012 created" }], result: "Failover complete. Traffic rerouted via backup ISP. Zero user impact due to sub-4s failover.", targetAsset: "CORE-SW-01" }),
    storage.createPlaybookExecution({ playbookId: playbooks[7].id, agentId: automationAgent.id, status: "completed", triggerReason: "API Gateway pods CPU at 82% for 8 minutes, Memory at 76%", actionsTaken: [{ step: 1, result: "Current: 3 replicas, avg CPU 82%, avg Memory 76%" }, { step: 2, result: "Calculated optimal: 5 replicas" }, { step: 3, result: "HPA updated: minReplicas=5, maxReplicas=10" }, { step: 4, result: "2 new pods ready in 23 seconds" }, { step: 5, result: "Load evenly distributed, CPU dropped to 48%" }], result: "Auto-scaled from 3 to 5 replicas. CPU normalized to 48%. No SLA impact.", targetAsset: "K8S-MASTER-01" }),
    storage.createPlaybookExecution({ playbookId: playbooks[4].id, agentId: iotAgent.id, status: "running", triggerReason: "New firmware v2.2.0 available for Particle Argon mesh devices", actionsTaken: [{ step: 1, result: "Firmware checksum verified: SHA256 match" }, { step: 2, result: "Deployed to 25 canary devices (10%)" }, { step: 3, result: "Monitoring canary group... 32 minutes elapsed" }], result: null, targetAsset: "WH-SENSOR-MESH" }),
    storage.createPlaybookExecution({ playbookId: playbooks[6].id, agentId: complianceAgent.id, status: "completed", triggerReason: "Scheduled compliance scan - CIS benchmark check", actionsTaken: [{ step: 1, result: "Scanned 42 Linux servers against CIS Level 2" }, { step: 2, result: "Found 7 drifted configurations across 3 servers" }, { step: 3, result: "Corrected: SSH MaxAuthTries (3 servers), password complexity (2 servers), audit logging (2 servers)" }, { step: 4, result: "Re-scan passed: 100% compliance" }, { step: 5, result: "Report generated: compliance-report-2026-03-03.pdf" }], result: "7 configuration drifts remediated across 3 servers. Full CIS Level 2 compliance restored.", targetAsset: "Linux Server Fleet" }),
    storage.createPlaybookExecution({ playbookId: playbooks[9].id, agentId: securityAgent.id, status: "completed", triggerReason: "Workstation WS-0234 outbound traffic 4.7x standard deviation above baseline", actionsTaken: [{ step: 1, result: "Captured 500MB traffic sample, detected data exfiltration pattern" }, { step: 2, result: "Host moved to VLAN 999 (quarantine)" }, { step: 3, result: "Perimeter block rule FW-QUAR-0891 applied" }, { step: 4, result: "Critical incident INC-SEC-0034 created" }, { step: 5, result: "Memory dump and disk image collection initiated" }], result: "WS-0234 isolated. 2.3GB suspicious outbound transfer stopped. Forensic investigation initiated.", targetAsset: "WS-0234" }),
  ]);

  const metricSources = [
    { id: cmdbItemsCreated[0].id, name: "FW-PROD-01", metrics: [{ name: "cpu_usage", value: 34, unit: "%", status: "normal" }, { name: "memory_usage", value: 62, unit: "%", status: "normal" }, { name: "throughput", value: 847, unit: "Mbps", status: "normal" }, { name: "active_sessions", value: 12847, unit: "sessions", status: "normal" }, { name: "dropped_packets", value: 23, unit: "pkt/s", status: "normal" }] },
    { id: cmdbItemsCreated[2].id, name: "DB-PROD-01", metrics: [{ name: "cpu_usage", value: 78, unit: "%", status: "warning" }, { name: "memory_usage", value: 91, unit: "%", status: "critical" }, { name: "disk_usage", value: 67, unit: "%", status: "normal" }, { name: "active_connections", value: 245, unit: "conn", status: "warning" }, { name: "query_latency", value: 12.4, unit: "ms", status: "normal" }, { name: "iops", value: 8400, unit: "ops/s", status: "normal" }] },
    { id: cmdbItemsCreated[6].id, name: "APP-WEB-01", metrics: [{ name: "cpu_usage", value: 45, unit: "%", status: "normal" }, { name: "memory_usage", value: 58, unit: "%", status: "normal" }, { name: "request_rate", value: 1247, unit: "req/s", status: "normal" }, { name: "error_rate", value: 0.3, unit: "%", status: "normal" }, { name: "response_time", value: 89, unit: "ms", status: "normal" }] },
    { id: cmdbItemsCreated[10].id, name: "CORE-SW-01", metrics: [{ name: "cpu_usage", value: 22, unit: "%", status: "normal" }, { name: "bandwidth_utilization", value: 4.2, unit: "Gbps", status: "normal" }, { name: "port_errors", value: 12, unit: "err/s", status: "warning" }, { name: "uptime", value: 99.997, unit: "%", status: "normal" }] },
    { id: cmdbItemsCreated[14].id, name: "HVAC-DC1-01", metrics: [{ name: "supply_temp", value: 18.2, unit: "°C", status: "normal" }, { name: "return_temp", value: 24.8, unit: "°C", status: "normal" }, { name: "humidity", value: 45, unit: "%", status: "normal" }, { name: "power_consumption", value: 12.4, unit: "kW", status: "normal" }] },
    { id: cmdbItemsCreated[15].id, name: "TEMP-SENSOR-01", metrics: [{ name: "temperature", value: 21.3, unit: "°C", status: "normal" }, { name: "humidity", value: 42, unit: "%", status: "normal" }, { name: "battery_level", value: 87, unit: "%", status: "normal" }] },
    { id: cmdbItemsCreated[19].id, name: "PDU-DC1-R01", metrics: [{ name: "power_draw", value: 4.8, unit: "kW", status: "normal" }, { name: "current", value: 21.2, unit: "A", status: "normal" }, { name: "voltage", value: 227, unit: "V", status: "normal" }, { name: "power_factor", value: 0.98, unit: "", status: "normal" }] },
    { id: cmdbItemsCreated[7].id, name: "VPN-PRIMARY", metrics: [{ name: "active_tunnels", value: 342, unit: "tunnels", status: "normal" }, { name: "bandwidth", value: 1.8, unit: "Gbps", status: "normal" }, { name: "cpu_usage", value: 56, unit: "%", status: "normal" }, { name: "concurrent_users", value: 342, unit: "users", status: "normal" }] },
    { id: cmdbItemsCreated[20].id, name: "K8S-MASTER-01", metrics: [{ name: "pod_count", value: 128, unit: "pods", status: "normal" }, { name: "node_cpu_avg", value: 48, unit: "%", status: "normal" }, { name: "node_memory_avg", value: 62, unit: "%", status: "normal" }, { name: "pending_pods", value: 0, unit: "pods", status: "normal" }] },
    { id: cmdbItemsCreated[13].id, name: "UPS-DC1-01", metrics: [{ name: "load", value: 67, unit: "%", status: "normal" }, { name: "battery_runtime", value: 18, unit: "min", status: "normal" }, { name: "input_voltage", value: 228, unit: "V", status: "normal" }, { name: "output_voltage", value: 230, unit: "V", status: "normal" }, { name: "battery_health", value: 94, unit: "%", status: "normal" }] },
  ];

  for (const source of metricSources) {
    for (const m of source.metrics) {
      await storage.createTelemetryMetric({ sourceId: source.id, sourceName: source.name, metricName: m.name, metricValue: m.value, unit: m.unit, status: m.status });
    }
  }

  await Promise.all([
    storage.createAgentActivity({ agentId: networkAgent.id, action: "Network Topology Scan Complete", details: "Scanned 18 network devices via SNMP v3. Discovered 2 new access points and verified 16 existing devices. All paths redundant.", relatedEntityType: "connector", autonomous: true }),
    storage.createAgentActivity({ agentId: automationAgent.id, action: "Auto-Remediation: Service Restart", details: "Detected nginx failure on APP-WEB-01. Automatically restarted service. Downtime: 47 seconds. Service healthy.", relatedEntityType: "playbook_execution", autonomous: true }),
    storage.createAgentActivity({ agentId: securityAgent.id, action: "Threat Blocked: Brute Force IP", details: "Blocked IP 192.168.45.102 at firewall after 847 failed SSH attempts targeting DB-PROD-01. Auto-unblock in 24h.", relatedEntityType: "playbook_execution", autonomous: true }),
    storage.createAgentActivity({ agentId: iotAgent.id, action: "IoT Firmware Rollout Initiated", details: "Started staged firmware update v2.2.0 for Particle Argon mesh. 25 canary devices updated, monitoring for anomalies.", relatedEntityType: "playbook_execution", autonomous: true }),
    storage.createAgentActivity({ agentId: complianceAgent.id, action: "Compliance Drift Remediated", details: "Detected and auto-corrected 7 CIS benchmark violations across 3 Linux servers. Full compliance restored.", relatedEntityType: "playbook_execution", autonomous: true }),
    storage.createAgentActivity({ agentId: patchAgent.id, action: "CVE Assessment Complete", details: "Evaluated 23 new CVEs from NVD feed. 3 critical (CVSS >9.0) affecting 8 servers. Auto-patch scheduled for maintenance window.", relatedEntityType: "cmdb", autonomous: true }),
    storage.createAgentActivity({ agentId: networkAgent.id, action: "Auto-Failover: WAN Link", details: "Primary WAN link degraded (340ms, 8.2% loss). Automatically failed over to backup ISP. Zero user impact.", relatedEntityType: "playbook_execution", autonomous: true }),
    storage.createAgentActivity({ agentId: automationAgent.id, action: "Auto-Scale: Kubernetes Pods", details: "API Gateway pods scaled from 3 to 5 replicas. CPU usage dropped from 82% to 48%. No SLA impact.", relatedEntityType: "playbook_execution", autonomous: true }),
    storage.createAgentActivity({ agentId: securityAgent.id, action: "Host Quarantined: WS-0234", details: "Anomalous outbound traffic detected (4.7x baseline). Host isolated to quarantine VLAN. Forensic collection initiated.", relatedEntityType: "playbook_execution", autonomous: true }),
    storage.createAgentActivity({ agentId: automationAgent.id, action: "Disk Cleanup: LOG-COLLECTOR-01", details: "Disk usage 91% → 52%. Compressed 847 log files, freed 20.4GB. No volume extension needed.", relatedEntityType: "playbook_execution", autonomous: true }),
    storage.createAgentActivity({ agentId: iotAgent.id, action: "Sensor Anomaly Detected", details: "Temperature sensor TEMP-SENSOR-02 reporting erratic readings (±8°C in 30 seconds). Scheduled physical inspection.", relatedEntityType: "telemetry", autonomous: true }),
    storage.createAgentActivity({ agentId: networkAgent.id, action: "Port Flapping Remediated", details: "CORE-SW-01 port Gi1/0/24 flapping detected. Port disabled, traffic rerouted via Gi1/0/25. Cable replacement ordered.", relatedEntityType: "cmdb", autonomous: true }),
    storage.createAgentActivity({ agentId: incidentAgent.id, action: "Incident Auto-Triaged", details: "IoT sensor latency spike auto-classified as High severity. Assigned to IoT Controller agent for investigation.", relatedEntityType: "incident", autonomous: true }),
    storage.createAgentActivity({ agentId: masterAgent.id, action: "Agent Coordination: Multi-Agent Response", details: "Coordinated Security Monitor + Network Monitor + Automation Engine for WS-0234 data exfiltration response. 3-agent collaborative remediation.", relatedEntityType: "agent", autonomous: true }),
  ]);
}
