import { useState, useEffect, useRef } from "react";
import { useLocation } from "wouter";
import { X, Bot, ChevronRight, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

interface PageTip {
  title: string;
  tips: string[];
  icon?: string;
}

const PAGE_TIPS: Record<string, PageTip> = {
  "/dashboard": {
    title: "Crews & Agents",
    tips: [
      "This is your organization chart — departments are called 'Crews' and roles are 'Agents'.",
      "Start by assigning yourself (or a team member) to a role. Click any agent card and use the 'Assign' action to allocate a human to that position.",
      "Once a human is assigned, you can enable an 'AI Shadow' — an autonomous AI agent that works alongside the human, handling routine tasks and providing real-time insights.",
      "The AI Shadow learns from the role's responsibilities and can monitor infrastructure, generate reports, and recommend actions — all under human oversight.",
      "Click any agent card to see their full job description, responsibilities, AI capabilities, and cost comparison (AI vs. human).",
      "Try the search bar at the top to quickly find agents by name, department, or skill.",
    ],
  },
  "/subscriptions": {
    title: "Active Agents",
    tips: [
      "This page shows all your active AI agent subscriptions and human assignments.",
      "Each card shows the agent's department, role level, and monthly cost.",
      "You can compare AI agent cost vs. equivalent human salary to see savings.",
      "Click an agent to jump to their dedicated performance dashboard.",
    ],
  },
  "/recommendations": {
    title: "AI Recommendations",
    tips: [
      "Describe what you need in the text box and our AI will recommend the best agents for the job.",
      "You can also select from predefined goals like 'Strengthen Security' or 'Optimize Infrastructure'.",
      "Previous recommendations are saved below — click any to review or act on them.",
      "Approving a recommendation will subscribe the suggested AI agents to your organization.",
    ],
  },
  "/infrastructure/cockpit": {
    title: "Infrastructure Cockpit",
    tips: [
      "This is your central command center — everything about your infrastructure at a glance.",
      "The Health Matrix shows category-level health gauges. Click any to drill into details.",
      "Discovery Probes at the bottom show real-time health of your deployed monitoring agents.",
      "The mini calendar shows upcoming scheduled AI activities. Click it to open the full calendar.",
      "Alert cards are color-coded by severity — click any to jump to Event Management.",
    ],
  },
  "/infrastructure/configure": {
    title: "Probe Configuration",
    tips: [
      "Probes are lightweight agents you deploy on servers to collect metrics and telemetry.",
      "Click 'Add Probe' to create a new probe — you'll get a deployment script to run on your server.",
      "Each probe supports different protocols: WMI for Windows, SNMP for network devices, SSH for Linux.",
      "After deploying, the probe will auto-enroll and start sending heartbeats within 2 minutes.",
    ],
  },
  "/infrastructure/discovery": {
    title: "Network Discovery",
    tips: [
      "Discovery scans your network to find devices, servers, and services automatically.",
      "Discovered assets appear in the Asset Management page for monitoring and analysis.",
      "Each scan uses the credentials and probe configurations you've set up.",
    ],
  },
  "/infrastructure/assets": {
    title: "Asset Management",
    tips: [
      "All your discovered devices and servers are listed here with their current status.",
      "Click any asset to see detailed info: hardware specs, software inventory, metrics, and risk score.",
      "The 'Multi-Agent Scan' button triggers all your AI agents to analyze an asset simultaneously.",
      "Use filters to narrow by type (server, workstation, network), OS, or health status.",
    ],
  },
  "/infrastructure/events": {
    title: "Event Management",
    tips: [
      "Events are alerts and incidents generated by your probes and AI agents.",
      "Click any event to see AI-powered Root Cause Analysis and recommended remediation.",
      "You can acknowledge, escalate, or auto-remediate events directly from this view.",
      "Critical events with remediation scripts go through an approval workflow before execution.",
    ],
  },
  "/infrastructure/service-metrics": {
    title: "Service Metrics",
    tips: [
      "This is your metrics catalog — CPU, memory, disk, network, security, and more.",
      "Switch between Metric View, Device View, and Mission Critical View using the tabs.",
      "The 'AI Auto-Assign' button lets AI agents intelligently assign relevant metrics to devices.",
      "Mission Critical groups let you define business applications and monitor their aggregate health.",
    ],
  },
  "/infrastructure/applications": {
    title: "Application Monitor",
    tips: [
      "AI discovers and maps applications running across your infrastructure.",
      "Business Application Topologies show how services depend on each other.",
      "Click any application to see its dependency graph and impact analysis.",
    ],
  },
  "/infrastructure/performance": {
    title: "Performance Analytics",
    tips: [
      "The fleet heatmap shows health status across all devices at a glance.",
      "KPI stat cards track key performance indicators with trend arrows.",
      "Filter by category to focus on specific infrastructure segments.",
    ],
  },
  "/infrastructure/calendar": {
    title: "Activity Calendar",
    tips: [
      "This calendar shows all AI-scheduled maintenance and operational activities.",
      "Activities are color-coded: blue = predictive, green = preventive, amber = prescriptive.",
      "Click any activity to approve, skip, or mark as completed.",
      "AI agents autonomously schedule activities based on their operational insights.",
      "Nothing runs without your approval — every activity has a human approval gate.",
    ],
  },
  "/agent-matrix": {
    title: "Agent Matrix",
    tips: [
      "The matrix shows all your AI agents with their departments, metrics, and performance scores.",
      "Click any agent row to jump to their individual dashboard with detailed analytics.",
      "Agents with a green status are actively monitoring and producing insights.",
      "The accuracy and hallucination columns help you assess AI reliability.",
    ],
  },
  "/agent-console": {
    title: "Ops Console",
    tips: [
      "This is a real-time terminal showing AI agent operations as they execute.",
      "Each task shows step-by-step progress with timestamps and status indicators.",
      "Use this to monitor what your AI agents are doing behind the scenes.",
    ],
  },
  "/agent-chat": {
    title: "Agent Chat",
    tips: [
      "Chat naturally with your AI agents — ask about infrastructure, request analysis, or get advice.",
      "The AI automatically routes your question to the most relevant agent based on expertise.",
      "Try asking things like 'What's the health of my Windows servers?' or 'Any security concerns?'",
      "Conversation history is preserved so agents have context from previous discussions.",
    ],
  },
  "/incidents": {
    title: "Incident Management",
    tips: [
      "This is your ITIL-aligned Incident Management dashboard — track and resolve disruptions to normal service operation.",
      "The KPI cards at the top show Total, Open, Investigating, Resolved, Critical counts, and Mean Time to Resolution (MTTR).",
      "The pipeline bar visualizes the ITIL lifecycle: Open → Investigating → In Progress → Resolved. Click to filter by status.",
      "The severity distribution bar shows the breakdown of incidents by severity (Critical, High, Medium, Low).",
      "Use the action buttons on each incident row to advance its status through the ITIL workflow — the system validates valid transitions.",
      "Click any incident to see full details including description, resolution time, and linked service requests.",
    ],
  },
  "/problems": {
    title: "Problem Management",
    tips: [
      "Problem Management focuses on identifying root causes of recurring incidents and preventing future disruptions.",
      "The KPI cards track Total, Open, Investigating, Root Cause Identified, Known Errors, Resolved, and Avg Resolution Time.",
      "The pipeline shows the ITIL lifecycle: Open → Investigating → Root Cause Identified → Resolved.",
      "A 'Known Error' is a problem with a documented root cause and workaround — these help speed up future incident resolution.",
      "Use the filters to narrow down by status, priority, or category.",
      "Click any problem to see affected services, workarounds, and resolution details.",
    ],
  },
  "/changes": {
    title: "Change Management",
    tips: [
      "Change Management controls modifications to your IT environment through a structured approval process.",
      "KPI cards show Total, Pending Review, Approved, Scheduled, Completed, Rejected/Failed, High Risk count, and Success Rate %.",
      "The pipeline follows the ITIL lifecycle: Draft → Submitted → Under Review → Approved → Scheduled → Implemented → Closed.",
      "The risk distribution bar shows the breakdown of changes by risk level (Critical, High, Medium, Low).",
      "Each change tracks impact assessment and rollback plans to minimize risk.",
      "Changes typically require committee approval (CAB) — see the Workflows page for approval gate status.",
    ],
  },
  "/service-requests": {
    title: "Service Requests",
    tips: [
      "Service Requests handle standard user requests like access provisioning, software installation, and equipment orders.",
      "KPI cards show Total, Open, In Progress, Fulfilled, Overdue, SLA Compliance %, and Avg Resolution time.",
      "The pipeline follows: New → Assigned → In Progress → On Hold → Pending Approval → Fulfilled → Closed.",
      "SLA indicators (green/amber/red) show whether each request is on track, at risk, or breached.",
      "New service requests of type 'Incident Report' automatically create a linked Incident record.",
      "AI agents are auto-assigned to requests based on type — e.g., access requests route to Security Monitor.",
    ],
  },
  "/leaderboard": {
    title: "Gamified Leaderboard",
    tips: [
      "The Leaderboard ranks your AI agents by XP earned from resolving incidents and service requests.",
      "The top 3 agents are displayed on a podium with rank badges — from Bronze all the way to Legendary.",
      "XP formula: 100 per incident resolved, 50 per SR, 200 bonus for critical issues, 75 speed bonus for resolutions under 2 hours.",
      "Agents level up every 500 XP. Ranks progress: Bronze → Silver → Gold → Platinum → Diamond → Legendary (every 3 levels).",
      "Use this page to see which agents are most productive and identify performance trends.",
    ],
  },
  "/on-call-roster": {
    title: "On-Call Roster",
    tips: [
      "The On-Call Roster shows who is available to handle human tasks at any point in time.",
      "KPI cards display Total Personnel, Available Now, On Call, Utilization %, and Active Tasks across your team.",
      "The availability distribution bar shows the breakdown: Available, Busy, On Call, On Break, Off Duty.",
      "Each person shows their current workload bar, shift times, contact info, and assigned role.",
      "Click the edit button on any person to update their availability status, shift times, or workload capacity.",
      "Expired shifts are auto-detected — the system flags personnel whose shift has ended.",
    ],
  },
  "/workflows": {
    title: "Workflow Orchestration",
    tips: [
      "Workflows are multi-stage orchestration pipelines that coordinate tasks, approvals, and automated actions across your organization.",
      "The KPI cards at the top show Total Workflows, Active, Pending Approval gates, Completed, and Committee count.",
      "Switch between the 'Workflows' and 'Committees' tabs to manage pipelines and approval bodies separately.",
      "Each workflow card shows its status, process type (sequential/parallel/conditional), stage progress bar, and pending approval gates.",
      "Click any workflow to see the interactive stage timeline — stages are color-coded by type: task (blue), approval gate (purple), automated (cyan), notification (amber).",
      "Approval gates require committee votes — use the Approve/Reject buttons in the workflow detail to cast votes toward the quorum.",
      "Committees are governance bodies (CAB, Security Review Board, etc.) that review approval gates. Click a committee card to manage its members and chair.",
    ],
  },
  "/tasks": {
    title: "AI Agent Tasks",
    tips: [
      "Tasks are work items assigned to AI agents — click 'Run Agent' to have GPT-4o autonomously execute the task and produce real output.",
      "The KPI cards show Total, Queued, Executing, Completed, Failed, and Critical task counts.",
      "Hit the 'Run Agent' button on any pending task — the AI agent will analyze the description, context, and expected deliverable, then produce professional output.",
      "While executing, the task card glows blue with a spinner — the AI is thinking. Output appears automatically when done.",
      "Click any task row to open the detail dialog showing the full AI-generated output, context, and completion timestamp.",
      "Failed tasks can be retried with the 'Retry' button — the agent will re-attempt execution from scratch.",
      "Tasks can be linked to workflow stages — when a workflow stage is a 'task' type, it references work tracked here.",
    ],
  },
  "/knowledge-base": {
    title: "Knowledge Base",
    tips: [
      "The Knowledge Base is your centralized repository for ITIL best practices, IT procedures, and organizational knowledge.",
      "Create new articles to capture solutions from resolved incidents, problems, and completed tasks.",
      "Search the knowledge base by keyword, category, or tags to find quick answers and reduce AI query time.",
      "When you run tasks, completed solutions are automatically captured into the KB to grow your knowledge over time.",
      "Articles are marked as 'Published' (visible to all) or 'Draft' (private). Use drafts for works-in-progress.",
      "The 'Most Helpful' ranking shows which articles your team finds most useful — popular articles rise to the top.",
      "AI agents use the knowledge base as a first-line reference before querying GPT-4o, reducing costs and improving consistency.",
    ],
  },
  "/bcp-drp": {
    title: "BCP / DRP",
    tips: [
      "Business Continuity & Disaster Recovery plans ensure your organization can maintain operations during disruptions. Define RTO/RPO targets, recovery strategies, and test your DR procedures regularly.",
    ],
  },
};

function getPageTip(pathname: string): PageTip | null {
  if (PAGE_TIPS[pathname]) return PAGE_TIPS[pathname];
  if (pathname.startsWith("/infrastructure/agent-dashboard")) {
    return {
      title: "Agent Dashboard",
      tips: [
        "This is the individual dashboard for a specific AI agent showing their full operational profile.",
        "The hero section shows the agent's role, department, and key performance rings.",
        "Scroll down to see assigned metrics, operational intelligence, and maintenance activities.",
        "Best practices are AI-generated recommendations tailored to this agent's responsibilities.",
      ],
    };
  }
  for (const key of Object.keys(PAGE_TIPS)) {
    if (pathname.startsWith(key)) return PAGE_TIPS[key];
  }
  return null;
}

const DISMISSED_KEY = "holocron-assistant-dismissed";

export function AiAssistantAvatar() {
  const [location] = useLocation();
  const [isOpen, setIsOpen] = useState(false);
  const [tipIndex, setTipIndex] = useState(0);
  const [dismissed, setDismissed] = useState(() => localStorage.getItem(DISMISSED_KEY) === "true");
  const popoverRef = useRef<HTMLDivElement>(null);
  const buttonRef = useRef<HTMLButtonElement>(null);

  const pageTip = getPageTip(location);

  useEffect(() => {
    setIsOpen(false);
    setTipIndex(0);
  }, [location]);

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (
        isOpen &&
        popoverRef.current &&
        !popoverRef.current.contains(e.target as Node) &&
        buttonRef.current &&
        !buttonRef.current.contains(e.target as Node)
      ) {
        setIsOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [isOpen]);

  if (dismissed || !pageTip) return null;

  const currentTip = pageTip.tips[tipIndex];
  const hasNext = tipIndex < pageTip.tips.length - 1;
  const hasPrev = tipIndex > 0;

  return (
    <div className="fixed bottom-5 right-5 z-[100]" data-testid="ai-assistant-container">
      {isOpen && (
        <div
          ref={popoverRef}
          className="absolute bottom-16 right-0 w-[320px] max-w-[85vw] animate-in slide-in-from-bottom-2 fade-in duration-200"
          data-testid="ai-assistant-popover"
        >
          <div className="bg-card border border-border rounded-xl shadow-2xl overflow-hidden">
            <div className="h-1 bg-gradient-to-r from-violet-500 via-blue-500 to-cyan-500" />

            <div className="p-4">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2">
                  <div className="h-6 w-6 rounded-full bg-violet-500/15 flex items-center justify-center">
                    <Sparkles className="h-3.5 w-3.5 text-violet-400" />
                  </div>
                  <span className="text-xs font-bold text-foreground">{pageTip.title}</span>
                </div>
                <button
                  onClick={() => setIsOpen(false)}
                  className="text-muted-foreground hover:text-foreground transition-colors"
                  data-testid="button-close-assistant"
                >
                  <X className="h-3.5 w-3.5" />
                </button>
              </div>

              <p className="text-[12px] leading-relaxed text-muted-foreground mb-3" data-testid="text-assistant-tip">
                {currentTip}
              </p>

              <div className="flex items-center justify-between">
                <div className="flex items-center gap-1">
                  {pageTip.tips.map((_, i) => (
                    <button
                      key={i}
                      onClick={() => setTipIndex(i)}
                      className={`h-1.5 rounded-full transition-all duration-300 cursor-pointer ${
                        i === tipIndex ? "w-4 bg-violet-400" : "w-1.5 bg-muted-foreground/30 hover:bg-muted-foreground/50"
                      }`}
                      data-testid={`dot-tip-${i}`}
                    />
                  ))}
                </div>

                <div className="flex items-center gap-1">
                  {hasPrev && (
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-6 px-2 text-[10px]"
                      onClick={() => setTipIndex(tipIndex - 1)}
                      data-testid="button-prev-tip"
                    >
                      Back
                    </Button>
                  )}
                  {hasNext && (
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-6 px-2 text-[10px]"
                      onClick={() => setTipIndex(tipIndex + 1)}
                      data-testid="button-next-tip"
                    >
                      Next
                      <ChevronRight className="h-3 w-3 ml-0.5" />
                    </Button>
                  )}
                </div>
              </div>
            </div>

            <div className="border-t border-border/50 px-4 py-2 flex justify-end">
              <button
                className="text-[9px] text-muted-foreground/60 hover:text-muted-foreground transition-colors"
                onClick={() => {
                  localStorage.setItem(DISMISSED_KEY, "true");
                  setDismissed(true);
                }}
                data-testid="button-dismiss-assistant"
              >
                Don't show again
              </button>
            </div>
          </div>
        </div>
      )}

      <button
        ref={buttonRef}
        onClick={() => setIsOpen(!isOpen)}
        className={`group relative h-12 w-12 rounded-full shadow-lg transition-all duration-300 flex items-center justify-center ${
          isOpen
            ? "bg-violet-600 shadow-violet-500/30 scale-95"
            : "bg-gradient-to-br from-violet-600 to-blue-600 shadow-violet-500/20 hover:shadow-violet-500/40 hover:scale-105"
        }`}
        data-testid="button-ai-assistant"
        title="Need help? Click for tips about this page"
      >
        <Bot className={`h-6 w-6 text-white transition-transform duration-300 ${isOpen ? "rotate-12" : "group-hover:rotate-12"}`} />

        {!isOpen && (
          <span className="absolute -top-0.5 -right-0.5 h-3 w-3 rounded-full bg-emerald-400 border-2 border-card" />
        )}
      </button>
    </div>
  );
}
